- name: LAMP Stack Deployment
  hosts: webservers
  become: true
  vars_files:
    - group_vars/secure.yml

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Enable and start Apache service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Secure MySQL installation
      mysql_secure_installation:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        root_password: "{{ mysql_root_password }}"
        remove_anonymous_users: yes
        disallow_root_login_remotely: yes
        remove_test_database: yes

    - name: Create a MySQL database
      mysql_db:
        name: myapp
        state: present

    - name: Create a MySQL user
      mysql_user:
        name: myapp_user
        password: "{{ mysql_app_password }}"
        priv: 'myapp.*:ALL'
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install PHP MySQL module
      apt:
        name: php-mysql
        state: present

    - name: Restart Apache to apply PHP module
      service:
        name: apache2
        state: restarted
